---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Role no longer maintained
  ansible.builtin.fail:
    msg: This role is no longer maintained
  when: arch_fonts_skip_deprecation_message | default(true) | bool

- name: install some fonts
  become: yes
  pacman:
    name: '{{ arch_fonts }}'
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Archlinux'

- name: excuse if not Arch
  debug:
    msg: "We are realy sorry, but this role uses packages they are only available on arch. Please feel free to expand it!"
  when: ansible_os_family != 'Archlinux'
